name: GenericItems
main: me.recursiveg.generictools.GenericTools
description: "Create highly customizable weapons and tools"
version: 0.1
depend: [NyaaUtils]
authors: [RecursiveG]

commands:
  generictools:
    description: The command for GenericItems
    aliases: gt
    permission: gt.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  gt.command:
    description: Base permission node for commands
    default: op
